<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container61cf6pi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container61cf6pi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container61cf6pi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container61cf6pi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container61cf6pi\appDevDebugProjectContainer([
    'container.build_hash' => '61cf6pi',
    'container.build_id' => 'b2fde513',
    'container.build_time' => 1591483458,
], __DIR__.\DIRECTORY_SEPARATOR.'Container61cf6pi');
